config/routes.rb
Eurasiarails::Application.routes.draw do

  devise_for :users
  root 'home#index'
  match "auth/:provider/callback" => "facebooks#create",:via => [:get,:post]
  resources :settings

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
       
  validates :real_name,:position_title,:section,:company_name,:company_tel,:company_email,:presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/facebooks_controller.rb
class FacebooksController < ApplicationController
  
  def create
    auth = request.env['omniauth.auth']
    user = User.find_by_email(auth["extra"]["raw_info"]["email"])
    if user
      user.token = auth["credentials"]["token"]
      user.secret = auth['credentials']['secret']
      user.save
      sign_in(:user, user, :bypass => true)
      redirect_to root_path
    else
      user = User.new(:email => auth["extra"]["raw_info"]["email"],:provider => auth["provider"],:uid => auth["uid"],:token => auth["credentials"]["token"],:secret =>auth['credentials']['secret'],:picture => auth["info"]["image"])
      user.save(:validate => false)
      sign_in(:user, user, :bypass => true)
      redirect_to edit_setting_path(user)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    if current_user
      @pages = FbGraph::User.me(current_user.token).accounts
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  
  
  def show
    @user = current_user
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:success] = "Updated successfully!"
      redirect_to root_path
    else
      flash[:error] = "Updation failed!"
      render :action => :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facebooks_helper.rb
module FacebooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/home/index.html.erb
<% if current_user %>
  <div>
    <div style="float:left;width:20%;">
      <ul class="list-inline">
        <% @pages.each do |page| %>
          <li><%= page.name %></li>
        <% end %>
        <li><%= link_to "add page","#" %></li>
      </ul>
    </div>
    <div style="float:left;width:80%;">
      <%#= image_tag current_user.picture %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Eurasiarails" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Eurasiarails</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav" style="float: right;">
              <% if !current_user %>
                <li><%= link_to "Register with Facebook", "/auth/facebook"  %></li>
                <li><%= link_to "Sign In with Facebook", "/auth/facebook"  %></li>
              <% else %>
                <li><div class="btn-group">
                    <button class="btn"><%= current_user.email.split("@")[0] %></button>
                    <button class="btn dropdown-toggle" data-toggle="dropdown">
                      <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                      <li><%= link_to "edit",edit_setting_path(current_user) %></li>
                      <li><%= link_to "profile",setting_path(current_user) %></li>
                      <li><%= link_to "Log Out", destroy_user_session_path,:method => :delete %></li>
                    </ul>
                </li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/settings/edit.html.erb
<%= form_for @user,:url => setting_path(@user),:method => :put do |f| %>
<%= f.error_messages %>
  <table>
    <tr>
      <td>Real Name:</td>
      <td><%= f.text_field :real_name %></td>
    </tr>
    <tr>
      <td>Position Title:</td>
      <td><%= f.text_field :position_title %></td>
    </tr>
    <tr>
      <td>Section:</td>
      <td><%= f.text_field :section %></td>
    </tr>
    <tr>
      <td>Company Name:</td>
      <td><%= f.text_field :company_name %></td>
    </tr>
    <tr>
      <td>Company Telephone:</td>
      <td><%= f.text_field :company_tel %></td>
    </tr>
    <tr>
      <td>Company Email:</td>
      <td><%= f.text_field :company_email %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit "Update",:class => "btn btn-success" %></td>
    </tr>
  </table>
<% end %>

app/views/settings/show.html.erb
  <table>
    <tr>
      <td>Real Name:</td>
      <td><%= @user.real_name %></td>
    </tr>
    <tr>
      <td>Position Title:</td>
      <td><%= @user.position_title %></td>
    </tr>
    <tr>
      <td>Section:</td>
      <td><%= @user.section %></td>
    </tr>
    <tr>
      <td>Company Name:</td>
      <td><%= @user.company_name %></td>
    </tr>
    <tr>
      <td>Company Telephone:</td>
      <td><%= @user.company_tel %></td>
    </tr>
    <tr>
      <td>Company Email:</td>
      <td><%= @user.company_email %></td>
    </tr>
  </table>